version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: 'rafaelfreitas.dev@gmail.com'
        PGADMIN_DEFAULT_PASSWORD: 'postgres'
    ports:
      - '16543:80'
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    name: rockelivery
    driver: bridge